const FETCH_LOADING = 'menu/FETCH_LOADING';
const FETCH_ERROR = 'menu/FETCH_ERROR';
const FETCH_SUCCESS_ALL_ITEMS = 'menu/FETCH_SUCCESS_ALL_ITEMS';
const FETCH_SUCCESS_ONE_ITEM = 'menu/FETCH_SUCCESS_ONE_ITEM';
const ADD_SUCCESS = 'menu/ADD_SUCCESS';
const DELETE_SUCCESS = 'menu/DELETE_SUCCESS';
const FETCH_SUCCESS_ALL_CATEGORIES = 'menu/FETCH_SUCCESS_ALL_CATEGORIES';
const CHANGE_FILTER = 'menu/CHANGE_FILTER';
const MODAL_OPEN = 'menu/MODAL_OPEN';
const MODAL_CLOSE = 'menu/MODAL_CLOSE';

export default {
  FETCH_LOADING,
  FETCH_ERROR,
  FETCH_SUCCESS_ALL_ITEMS,
  ADD_SUCCESS,
  DELETE_SUCCESS,
  FETCH_SUCCESS_ALL_CATEGORIES,
  CHANGE_FILTER,
  FETCH_SUCCESS_ONE_ITEM,
  MODAL_OPEN,
  MODAL_CLOSE,
};
