export default Object.freeze({
  HOME: '/',
  AUTH: '/auth',
  MENU: '/menu',
  MENU_ITEM: '/menu/:id',
  MENU_ADD_ITEM: '/menu/add',
  ORDER_HISTORY: '/order-history',
  CART: '/cart',
  ACCOUNT: '/account',
  PLANNER: '/planner',
  ABOUT: '/about',
  CONTACTS: '/contacts',
  DELIVERY: '/delivery',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
});
