const ADD_TO_CART = 'cart/ADD_TO_CART';
const REMOVE_FROM_CART = 'cart/REMOVE_FROM_CART';
const INCREASE_AMOUNT = 'cart/INCREASE_AMOUNT';
const DECREASE_AMOUNT = 'cart/DECREASE_AMOUNT';

export default {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  INCREASE_AMOUNT,
  DECREASE_AMOUNT,
};
